
title: UAC Bypass Using MSConfig Token Modification - Process
author: Christian Burkard
date: 2021/08/30
description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
detection:
  SELECTION_1:
    IntegrityLevel:
    - High
    - System
  SELECTION_2:
    ParentImage: '*\AppData\Local\Temp\pkgmgr.exe'
  SELECTION_3:
    CommandLine: '"C:\Windows\system32\msconfig.exe" -5'
  condition: (SELECTION_1 and SELECTION_2 and SELECTION_3)
falsepositives:
- Unknown
id: ad92e3f9-7eb6-460e-96b1-582b0ccbb980
level: high
logsource:
  category: process_creation
  product: windows
references:
- https://github.com/hfiref0x/UACME
status: experimental
tags:
- attack.defense_evasion
- attack.privilege_escalation
- attack.t1548.002
