
title: Using SettingSyncHost.exe as LOLBin
author: Anton Kutepov, oscd.community
date: 2020/02/05
description: Detects using SettingSyncHost.exe to run hijacked binary
detection:
  SELECTION_1:
    Image:
    - C:\Windows\System32\\*
    - C:\Windows\SysWOW64\\*
  SELECTION_2:
    ParentCommandLine: '*cmd.exe /c*'
  SELECTION_3:
    ParentCommandLine: '*RoamDiag.cmd*'
  SELECTION_4:
    ParentCommandLine: '*-outputpath*'
  condition: ( not (SELECTION_1) and (SELECTION_2 and SELECTION_3 and SELECTION_4))
falsepositives:
- unknown
fields:
- TargetFilename
- Image
id: b2ddd389-f676-4ac4-845a-e00781a48e5f
level: high
logsource:
  category: process_creation
  product: windows
modified: 2021/11/27
references:
- https://www.hexacorn.com/blog/2020/02/02/settingsynchost-exe-as-a-lolbin
status: test
tags:
- attack.execution
- attack.defense_evasion
- attack.t1574.008
